export const productData =  [
    {
        product_id:'123',
        name:'Off-White Basic Tee MN-TS-BS-WS23-001',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'black_basic_tee_mn-ts-bs-ws23-003_2_.webp',
        discount_price:'1250',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'124',
        name:'Black Basic Tee MN-TS-BS-WS23-003',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'coffee_basic_tee_mn-ts-bs-ws23-004_2_.webp',
        discount_price:'1350',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'125',
        name:' Coffee Basic Tee MN-TS-BS-WS23-004',
        price:'1600',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'expresso_basic_tee_mn-ts-bs-ws23-006_1_.webp',
        discount_price:'1350',
        sku:['m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'126',
        name:'Expresso Basic Tee MN-TS-BS-WS23-006',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'latte_basic_tee_mn-ts-bs-ws23-007_2_.webp',
        discount_price:'1350',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'127',
        name:'Latte Basic Tee MN-TS-BS-WS23-007',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'off-white_basic_tee_mn-ts-bs-ws23-001_2_.webp',
        discount_price:'1250',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'128',
        name:'Off-White Basic Tee MN-TS-BS-WS23-001',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'black_basic_tee_mn-ts-bs-ws23-003_2_.webp',
        discount_price:'1250',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'129',
        name:'Black Basic Tee MN-TS-BS-WS23-003',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'coffee_basic_tee_mn-ts-bs-ws23-004_2_.webp',
        discount_price:'1350',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'121',
        name:' Coffee Basic Tee MN-TS-BS-WS23-004',
        price:'1600',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'expresso_basic_tee_mn-ts-bs-ws23-006_1_.webp',
        discount_price:'1350',
        sku:['m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'122',
        name:'Expresso Basic Tee MN-TS-BS-WS23-006',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'latte_basic_tee_mn-ts-bs-ws23-007_2_.webp',
        discount_price:'1350',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },
    {
        product_id:'120',
        name:'Latte Basic Tee MN-TS-BS-WS23-007',
        price:'1500',
        category:'men',
        brand:'zeen',
        description:'men T-shirt for winter season',
        url:'off-white_basic_tee_mn-ts-bs-ws23-001_2_.webp',
        discount_price:'1250',
        sku:['s','m','l'],
        qty:1,
        edit:false
    },

]